import type {
  AnalyticsSnapshot,
  PapercutBacklog,
  PortfolioSnapshot,
  PromotionInbox,
  SkillsSnapshot,
} from "./types";

export const emptySnapshot: PortfolioSnapshot = {
  roots: [],
  repositories: [],
  products: [],
  groups: [],
  events: [],
  action_audits: [],
  provider_identities: [],
  remote_repositories: [],
  provider_status: {
    provider: "GitHub",
    state: "Not connected",
    message:
      "Connect GitHub through the existing credential manager to load remote context.",
    identity_count: 0,
    repository_count: 0,
  },
  quality: { audit_status: "Not configured", matched_repository_count: 0 },
  remediation: {
    schema_version: "pronto-remediation/v3",
    id: "",
    generated_at: new Date().toISOString(),
    source_refresh_id: null,
    status: "not_run",
    message: null,
    eligible_repository_ids: [],
    eligible_repository_paths: [],
    refresh_steps: [],
    excluded_repositories: [],
    closures: [],
    github_only_candidates: [],
    plans: [],
  },
  showcase: {
    schema_version: "pronto-showcase/v2",
    status: "Missing",
    contract_path: ".pronto/showcase-goal.json",
    reviewed_at: null,
    quality_bar_source: null,
    goal: {
      target_publishable_demo_count: 0,
      publishable_demo_count: 0,
      remaining_demo_count: 0,
      status: "Not configured",
    },
    scoring: null,
    public_queue: [],
    private_client_count: 0,
    projects: [],
    error: null,
  },
  retention_days: 90,
  generated_at: new Date().toISOString(),
  storage_path: "",
};

export const emptyAnalytics: AnalyticsSnapshot = {
  schema_version: "pronto-analytics/v2",
  generated_at: new Date().toISOString(),
  source: "Local refresh snapshots",
  freshness: "Unavailable until the first local refresh",
  range_days: 30,
  retention_days: 90,
  portfolio_samples: [],
  repositories: [],
  metric_catalog: [],
  findings: [],
  views: [],
  default_view_id: "curated",
};

export const emptySkills: SkillsSnapshot = {
  schema_version: "pronto-skills/v4",
  generated_at: new Date().toISOString(),
  freshness: "Unavailable until the first skills refresh",
  source: "Local skill roots; usage requires structured provider telemetry",
  recent_days: 30,
  roots: [],
  skills: [],
  telemetry_gap: "No skills refresh has been recorded.",
};

export const emptyPromotionInbox: PromotionInbox = {
  schema_version: "leverage-promotion-inbox/v1",
  visibility: "private",
  generated_at: new Date().toISOString(),
  source_root: "",
  candidates: [],
  counts: {
    total: 0,
    pending: 0,
    deferred: 0,
    rejected: 0,
    accepted: 0,
    complete: 0,
    drafts: 0,
  },
  coverage: null,
  discovery: null,
  errors: [],
  manual_review_required: true,
  jas_mutation: false,
  status: "unavailable",
  provenance_hash: "",
  message: "Promotion review is available in the Pronto desktop app.",
  jas_admission: null,
};

export const emptyPapercutBacklog: PapercutBacklog = {
  schema_version: "pronto-papercuts/v2",
  family: "design-audit",
  generated_at: new Date().toISOString(),
  papercuts: [],
  counts: {
    total: 0,
    open: 0,
    in_progress: 0,
    deferred: 0,
    resolved: 0,
    observations: 0,
    local_patterns: 0,
    cross_scope_patterns: 0,
    draft_proposals: 0,
  },
  observations: [],
  patterns: [],
  proposals: [],
  digests: [],
  health: {
    status: "healthy",
    database_writable: true,
    consecutive_failures: 0,
    spooled_events: 0,
    quarantined_events: 0,
    oldest_spool_at: null,
    last_success_at: null,
    warning: null,
    excerpt_retention_days: 90,
  },
};
