pub fn run_cli(arguments: Vec<String>) {
    let command = arguments.first().map(String::as_str).unwrap_or("status");
    let json = arguments.iter().any(|argument| argument == "--json");
    let path = store_path();
    match command {
        "help" | "-h" | "--help" => run_cli_arm_01(&arguments, json, &path, command),
        "workspace-policy" => run_cli_arm_02(&arguments, json, &path, command),
        "workspace-manifest" => run_cli_arm_03(&arguments, json, &path, command),
        "custody" => run_cli_arm_04(&arguments, json, &path, command),
        "skills" => run_cli_arm_05(&arguments, json, &path, command),
        "telescope" => run_cli_arm_38(&arguments, json, &path, command),
        "papercuts" => run_cli_arm_06(&arguments, json, &path, command),
        "behavior" => run_cli_arm_07(&arguments, json, &path, command),
        "change-matrix" => run_cli_arm_08(&arguments, json, &path, command),
        "refresh-skills" => run_cli_arm_09(&arguments, json, &path, command),
        "route" => run_cli_arm_10(&arguments, json, &path, command),
        "group" => run_cli_arm_11(&arguments, json, &path, command),
        "analytics" => run_cli_arm_12(&arguments, json, &path, command),
        "product" => run_cli_arm_13(&arguments, json, &path, command),
        "workspace" => run_cli_arm_14(&arguments, json, &path, command),
        "preflight" => run_cli_arm_15(&arguments, json, &path, command),
        "condition" => run_cli_arm_16(&arguments, json, &path, command),
        "settings" => run_cli_arm_17(&arguments, json, &path, command),
        "status" => run_cli_arm_18(&arguments, json, &path, command),
        "summary" => run_cli_arm_19(&arguments, json, &path, command),
        "doctor" => run_cli_arm_20(&arguments, json, &path, command),
        "next" => run_cli_arm_21(&arguments, json, &path, command),
        "fold" => run_cli_arm_22(&arguments, json, &path, command),
        "repo" => run_cli_arm_23(&arguments, json, &path, command),
        "attention" => run_cli_arm_24(&arguments, json, &path, command),
        "activity" => run_cli_arm_25(&arguments, json, &path, command),
        "prepare" => run_cli_arm_26(&arguments, json, &path, command),
        "release" => run_cli_arm_27(&arguments, json, &path, command),
        "remediation" => run_cli_arm_28(&arguments, json, &path, command),
        "refresh" => run_cli_arm_29(&arguments, json, &path, command),
        "refresh-batch" => run_cli_arm_30(&arguments, json, &path, command),
        "refresh-github" => run_cli_arm_31(&arguments, json, &path, command),
        "quality" => run_cli_arm_32(&arguments, json, &path, command),
        "root" => run_cli_arm_33(&arguments, json, &path, command),
        "clone" => run_cli_arm_34(&arguments, json, &path, command),
        "." => run_cli_arm_35(&arguments, json, &path, command),
        "open" => run_cli_arm_36(&arguments, json, &path, command),
        _ => run_cli_arm_37(&arguments, json, &path, command),
    }
}
