fn load_analytics_samples(
    connection: &SqliteConnection,
    repository_id: Option<&str>,
    cutoff: &str,
) -> Result<Vec<AnalyticsMetricSample>, String> {
    let mut samples = Vec::new();
    let mut statement = match repository_id {
        Some(_) => connection
            .prepare(
                "SELECT payload_json FROM analytics_samples
                 WHERE repository_id = ?1 AND observed_at >= ?2
                 ORDER BY observed_at, id",
            )
            .map_err(|error| format!("Could not prepare analytics query: {error}"))?,
        None => connection
            .prepare(
                "SELECT payload_json FROM analytics_samples
                 WHERE repository_id IS NULL AND observed_at >= ?1
                 ORDER BY observed_at, id",
            )
            .map_err(|error| format!("Could not prepare analytics query: {error}"))?,
    };
    match repository_id {
        Some(repository_id) => {
            let rows = statement
                .query_map(params![repository_id, cutoff], analytics_payload)
                .map_err(|error| format!("Could not read analytics samples: {error}"))?;
            for row in rows {
                let payload =
                    row.map_err(|error| format!("Could not decode analytics row: {error}"))?;
                samples.push(migrate_analytics_sample(
                    serde_json::from_str(&payload)
                        .map_err(|error| format!("Could not decode analytics sample: {error}"))?,
                ));
            }
        }
        None => {
            let rows = statement
                .query_map(params![cutoff], analytics_payload)
                .map_err(|error| format!("Could not read analytics samples: {error}"))?;
            for row in rows {
                let payload =
                    row.map_err(|error| format!("Could not decode analytics row: {error}"))?;
                samples.push(migrate_analytics_sample(
                    serde_json::from_str(&payload)
                        .map_err(|error| format!("Could not decode analytics sample: {error}"))?,
                ));
            }
        }
    }
    Ok(samples)
}

fn metric_definition(
    id: &str,
    label: &str,
    description: &str,
    unit: &str,
    denominator: &str,
    scope: &str,
    time_semantics: &str,
    window_days: Option<i64>,
    aggregation: &str,
    polarity: &str,
    source: &str,
    charts: &[&str],
) -> MetricDefinition {
    MetricDefinition {
        id: id.to_string(),
        label: label.to_string(),
        description: description.to_string(),
        unit: unit.to_string(),
        denominator: denominator.to_string(),
        scope: scope.to_string(),
        time_semantics: time_semantics.to_string(),
        window_days,
        aggregation: aggregation.to_string(),
        polarity: polarity.to_string(),
        source: source.to_string(),
        freshness: "local-refresh".to_string(),
        allowed_visualizations: charts.iter().map(|value| value.to_string()).collect(),
    }
}

fn analytics_metric_catalog() -> Vec<MetricDefinition> {
    vec![
        metric_definition(
            "git.commits.trailing_30_days",
            "Commits",
            "Local commits in the trailing 30-day window.",
            "commits",
            "portfolio",
            "portfolio",
            "trailing-window",
            Some(30),
            "sum",
            "neutral",
            "local-git",
            &["line", "bar", "table"],
        ),
        metric_definition(
            "git.ahead_commits",
            "Ahead commits",
            "Commits ahead of configured upstream branches.",
            "commits",
            "workspaces",
            "repository",
            "point-in-time",
            None,
            "sum",
            "lower-is-better",
            "local-git",
            &["diverging-bar", "bar", "table"],
        ),
        metric_definition(
            "git.behind_commits",
            "Behind commits",
            "Commits behind configured upstream branches.",
            "commits",
            "workspaces",
            "repository",
            "point-in-time",
            None,
            "sum",
            "lower-is-better",
            "local-git",
            &["diverging-bar", "bar", "table"],
        ),
        metric_definition(
            "conditions.active",
            "Active conditions",
            "Active deterministic portfolio conditions.",
            "conditions",
            "portfolio",
            "portfolio",
            "point-in-time",
            None,
            "sum",
            "lower-is-better",
            "local-refresh",
            &["line", "bar", "stacked-bar", "table"],
        ),
        metric_definition(
            "workspaces.dirty",
            "Dirty workspaces",
            "Workspaces with local changes.",
            "workspaces",
            "portfolio",
            "portfolio",
            "point-in-time",
            None,
            "sum",
            "lower-is-better",
            "local-git",
            &["line", "bar", "stacked-bar", "table"],
        ),
        metric_definition(
            "workspaces.unsynced",
            "Unsynced workspaces",
            "Workspaces ahead of or behind an upstream.",
            "workspaces",
            "portfolio",
            "portfolio",
            "point-in-time",
            None,
            "sum",
            "lower-is-better",
            "local-git",
            &["line", "bar", "stacked-bar", "table"],
        ),
        metric_definition(
            "workspaces.activity.active",
            "Active workspaces",
            "Workspaces with recent local activity.",
            "workspaces",
            "portfolio",
            "portfolio",
            "point-in-time",
            None,
            "sum",
            "neutral",
            "workspace-activity",
            &["line", "bar", "stacked-bar", "table"],
        ),
        metric_definition(
            "workspaces.activity.interrupted",
            "Interrupted workspaces",
            "Workspaces whose recent activity appears interrupted.",
            "workspaces",
            "portfolio",
            "portfolio",
            "point-in-time",
            None,
            "sum",
            "lower-is-better",
            "workspace-activity",
            &["line", "bar", "stacked-bar", "table"],
        ),
        metric_definition(
            "workspaces.activity.idle",
            "Idle workspaces",
            "Workspaces without recent observed activity.",
            "workspaces",
            "portfolio",
            "portfolio",
            "point-in-time",
            None,
            "sum",
            "neutral",
            "workspace-activity",
            &["line", "bar", "stacked-bar", "table"],
        ),
        metric_definition(
            "workspaces.activity.unknown",
            "Unknown activity",
            "Workspaces whose activity state is unavailable.",
            "workspaces",
            "portfolio",
            "portfolio",
            "point-in-time",
            None,
            "sum",
            "lower-is-better",
            "workspace-activity",
            &["line", "bar", "stacked-bar", "table"],
        ),
        metric_definition(
            "quality.maturity_score",
            "Maturity",
            "Imported quality maturity score.",
            "score-0-4",
            "scored repositories",
            "repository",
            "point-in-time",
            None,
            "average",
            "higher-is-better",
            "quality-runner",
            &["line", "scatter", "bar", "table"],
        ),
        metric_definition(
            "quality.maturity_evidence_coverage",
            "Maturity evidence coverage",
            "Share of applicable repository maturity pillars with imported evidence.",
            "ratio-0-1",
            "applicable maturity pillars",
            "repository",
            "point-in-time",
            None,
            "average",
            "higher-is-better",
            "quality-runner",
            &["line", "scatter", "bar", "heatmap", "table"],
        ),
        metric_definition(
            "quality.fresh_passing_ci_score",
            "Fresh-passing CI score",
            "Fresh passing CI, local, and Quality Runner evidence score.",
            "score-0-4",
            "scored repositories",
            "repository",
            "point-in-time",
            None,
            "average",
            "higher-is-better",
            "quality-runner",
            &["line", "scatter", "bar", "heatmap", "table"],
        ),
        metric_definition(
            "quality.evidence_score",
            "Fresh-passing CI score (legacy)",
            "Legacy v2 alias for fresh-passing CI evidence; it is not maturity evidence coverage.",
            "score-0-4",
            "scored repositories",
            "repository",
            "point-in-time",
            None,
            "average",
            "higher-is-better",
            "quality-runner",
            &["line", "scatter", "bar", "heatmap", "table"],
        ),
        metric_definition(
            "findings.total",
            "Detector findings",
            "Raw detector findings before disposition; maturity gaps are excluded.",
            "findings",
            "scanned repositories",
            "repository",
            "point-in-time",
            None,
            "sum",
            "lower-is-better",
            "quality-runner",
            &["line", "bar", "stacked-bar", "table"],
        ),
        metric_definition(
            "findings.high_severity",
            "High-severity detector findings",
            "High-severity findings emitted by code detectors.",
            "findings",
            "scanned repositories",
            "repository",
            "point-in-time",
            None,
            "sum",
            "lower-is-better",
            "quality-runner",
            &["line", "bar", "stacked-bar", "table"],
        ),
        metric_definition(
            "findings.detector_actionable",
            "Actionable detector findings",
            "Detector findings still requiring action after repository dispositions.",
            "findings",
            "scanned repositories",
            "repository",
            "point-in-time",
            None,
            "sum",
            "lower-is-better",
            "quality-runner",
            &["line", "bar", "stacked-bar", "table"],
        ),
        metric_definition(
            "findings.detector_unreviewed",
            "Unreviewed detector findings",
            "Detector findings without a current repository review disposition.",
            "findings",
            "scanned repositories",
            "repository",
            "point-in-time",
            None,
            "sum",
            "lower-is-better",
            "quality-runner",
            &["line", "bar", "stacked-bar", "table"],
        ),
        metric_definition(
            "findings.detector_total",
            "Detector findings",
            "Explicit detector finding count, separate from maturity gaps.",
            "findings",
            "scanned repositories",
            "repository",
            "point-in-time",
            None,
            "sum",
            "lower-is-better",
            "quality-runner",
            &["line", "bar", "stacked-bar", "table"],
        ),
        metric_definition(
            "maturity.gaps",
            "Maturity gaps",
            "Maturity dimensions below the maintained threshold; not code findings.",
            "gaps",
            "assessed repositories",
            "repository",
            "point-in-time",
            None,
            "sum",
            "lower-is-better",
            "quality-runner",
            &["line", "bar", "table"],
        ),
        metric_definition(
            "release.ready_repositories",
            "Release ready",
            "Repositories meeting Pronto-configured local release thresholds.",
            "repositories",
            "Pronto release rules configured",
            "portfolio",
            "point-in-time",
            None,
            "count",
            "higher-is-better",
            "local-release-rules",
            &["line", "bar", "table"],
        ),
        metric_definition(
            "release.configured_repositories",
            "Pronto release rules configured",
            "Repositories with a Pronto-configured local release threshold.",
            "repositories",
            "Pronto release rules configured",
            "portfolio",
            "point-in-time",
            None,
            "count",
            "neutral",
            "local-release-rules",
            &["line", "bar", "table"],
        ),
        metric_definition(
            "remediation.actions.open",
            "Open actions",
            "Remediation actions not yet started.",
            "actions",
            "remediation plans",
            "portfolio",
            "point-in-time",
            None,
            "sum",
            "lower-is-better",
            "remediation",
            &["line", "bar", "stacked-bar", "table"],
        ),
        metric_definition(
            "remediation.actions.in_progress",
            "In-progress actions",
            "Remediation actions currently in progress.",
            "actions",
            "remediation plans",
            "portfolio",
            "point-in-time",
            None,
            "sum",
            "neutral",
            "remediation",
            &["line", "bar", "stacked-bar", "table"],
        ),
        metric_definition(
            "remediation.actions.blocked",
            "Blocked actions",
            "Remediation actions with an explicit blocker.",
            "actions",
            "remediation plans",
            "portfolio",
            "point-in-time",
            None,
            "sum",
            "lower-is-better",
            "remediation",
            &["line", "bar", "stacked-bar", "table"],
        ),
        metric_definition(
            "remediation.actions.deferred",
            "Deferred actions",
            "Remediation actions with a recorded deferral.",
            "actions",
            "remediation plans",
            "portfolio",
            "point-in-time",
            None,
            "sum",
            "neutral",
            "remediation",
            &["line", "bar", "stacked-bar", "table"],
        ),
        metric_definition(
            "remediation.actions.verified",
            "Verified actions",
            "Remediation actions with verified completion evidence.",
            "actions",
            "remediation plans",
            "portfolio",
            "point-in-time",
            None,
            "sum",
            "higher-is-better",
            "remediation",
            &["line", "bar", "stacked-bar", "table"],
        ),
        metric_definition(
            "remediation.progress_percent",
            "Remediation progress",
            "Verified action weight as a share of non-deferred remediation weight.",
            "percent",
            "eligible remediation weight",
            "portfolio",
            "point-in-time",
            None,
            "latest",
            "higher-is-better",
            "remediation",
            &["line", "bar", "table"],
        ),
    ]
}
