include!("quality/part-01.rs");
include!("quality/part-02.rs");
include!("quality/part-03.rs");
include!("quality/part-04.rs");
include!("quality/part-05.rs");
include!("quality/part-06.rs");
include!("quality/part-07.rs");
include!("quality/part-08.rs");
include!("quality/part-09.rs");
include!("quality/part-10.rs");
include!("quality/part-11.rs");
include!("quality/part-12.rs");
include!("quality/part-13.rs");
include!("quality/part-14.rs");
include!("quality/part-15.rs");
#[cfg(test)]
mod tests {
    include!("quality/tests-01.rs");
    include!("quality/tests-02.rs");
    include!("quality/tests-03.rs");
    include!("quality/tests-04.rs");
    include!("quality/tests-05.rs");
    include!("quality/tests-06.rs");
}
