include!("remediation/part-01.rs");
include!("remediation/part-02.rs");
include!("remediation/part-03.rs");
include!("remediation/part-04.rs");
include!("remediation/part-05.rs");
include!("remediation/part-06.rs");
include!("remediation/part-07.rs");
include!("remediation/part-08.rs");
include!("remediation/part-09.rs");
include!("remediation/part-10.rs");
include!("remediation/part-11.rs");
include!("remediation/part-12.rs");
#[cfg(test)]
mod tests {
    include!("remediation/tests-01.rs");
    include!("remediation/tests-02.rs");
    include!("remediation/tests-03.rs");
    include!("remediation/tests-04.rs");
    include!("remediation/tests-05.rs");
}
